### ISSUE TITLE
gridについて

### ISSUE THREAD

**Issue by c0b2111568** [c0b2108596/ProjExD#5]
https://github.com/c0b2108596/ProjExD/blob/83122036b5d25dfc4e638b7ef42e6b352df2ae26/ex02/calc.py#L56
定数から計算して位置を設定するより、配置したい場所の数字を直接入れたほうがきれいかもしれません

**Comment by 46maru** [comment]
for文で回したところ以外は配置したい場所の数字を直接入力するように修正しました。
